/* Generated by SharpKit */
if (typeof(SharpKitSample) == "undefined")
    var SharpKitSample = {};
SharpKitSample.SampleClass = function ()
{
};
SharpKitSample.SampleClass.RunSample = function ()
{
     alert(5);;
};
